export interface Employee{
    id:string;
    fullName?:string;
    birthPlace?:string;
    birthDate?:string;
    phoneNumber?:string;
    email?:string;
    nik?:string;
    employeeId?:string;
    position?:string;
    positionDesc?:string;
    department?:string;
    departmentDesc?:string;
    dateStart?:string;
    dateEnd?:string;
    baseSalary?:number;
    bankAccount?:string;
    bankAccountNum?:string;
    isActive?:boolean;
}